/**
 * Trackside sound, synthesized.
 *
 * Every effect here is generated by the Web Audio API at the moment it plays —
 * there is not a single audio file in the project. That is deliberate: a room
 * full of people on conference wifi should not each be pulling down samples
 * before they can hear the lights go out, and a quiz that ships in one HTML
 * bundle should keep shipping in one HTML bundle.
 *
 * The palette is a timing screen, not an arcade: short square-wave blips for
 * keys, a clean rising interval when something goes right, a flat low buzz when
 * it does not. Nothing sustains for longer than a second.
 */

export type Sfx =
  | "key" // one correct keystroke while retyping the prompt
  | "typo" // a wrong character; the passage will not advance
  | "stage" // the prompt is fully typed, the answer field unlocks
  | "correct"
  | "wrong"
  | "hint"
  | "count" // one of the 3-2-1 beeps
  | "go" // lights out
  | "join"
  | "finish"
  | "ui"; // a button press

const STORE_KEY = "ggp_sound";

let ctx: AudioContext | null = null;
let master: GainNode | null = null;
let muted = readMuted();
const listeners = new Set<(m: boolean) => void>();

function readMuted(): boolean {
  try {
    return localStorage.getItem(STORE_KEY) === "off";
  } catch {
    return false; // a locked-down browser gets sound rather than silence
  }
}

/** Browsers refuse to start audio outside a gesture, so this runs on first play. */
function ensure(): AudioContext | null {
  if (typeof window === "undefined") return null;
  if (!ctx) {
    const Ctor = window.AudioContext ?? (window as unknown as { webkitAudioContext?: typeof AudioContext }).webkitAudioContext;
    if (!Ctor) return null;
    try {
      ctx = new Ctor();
    } catch {
      return null;
    }
    master = ctx.createGain();
    master.gain.value = 0.5; // headroom: several of these can overlap
    master.connect(ctx.destination);
  }
  if (ctx.state === "suspended") void ctx.resume();
  return ctx;
}

interface ToneOpts {
  freq: number;
  /** Slide to this frequency across the note; omitted means a flat tone. */
  to?: number;
  type?: OscillatorType;
  /** Seconds. */
  dur?: number;
  gain?: number;
  /** Seconds from now. */
  delay?: number;
}

function tone({ freq, to, type = "square", dur = 0.08, gain = 0.15, delay = 0 }: ToneOpts) {
  const ac = ensure();
  if (!ac || !master) return;
  const t0 = ac.currentTime + delay;
  const osc = ac.createOscillator();
  const env = ac.createGain();
  osc.type = type;
  osc.frequency.setValueAtTime(freq, t0);
  if (to !== undefined) osc.frequency.exponentialRampToValueAtTime(Math.max(1, to), t0 + dur);

  // A hard start or stop on a square wave is an audible click, so every note
  // gets a 4ms fade in and a ramp down to silence.
  env.gain.setValueAtTime(0.0001, t0);
  env.gain.exponentialRampToValueAtTime(gain, t0 + 0.004);
  env.gain.exponentialRampToValueAtTime(0.0001, t0 + dur);

  osc.connect(env).connect(master);
  osc.start(t0);
  osc.stop(t0 + dur + 0.02);
}

/** A filtered noise burst — used for the key click, where a pitch would read as melody. */
function click(gain = 0.05, dur = 0.02) {
  const ac = ensure();
  if (!ac || !master) return;
  const frames = Math.max(1, Math.floor(ac.sampleRate * dur));
  const buf = ac.createBuffer(1, frames, ac.sampleRate);
  const data = buf.getChannelData(0);
  for (let i = 0; i < frames; i++) {
    // Decaying white noise: the shape of a key bottoming out.
    data[i] = (Math.random() * 2 - 1) * (1 - i / frames) ** 3;
  }
  const src = ac.createBufferSource();
  src.buffer = buf;
  const hp = ac.createBiquadFilter();
  hp.type = "highpass";
  hp.frequency.value = 1400;
  const env = ac.createGain();
  env.gain.value = gain;
  src.connect(hp).connect(env).connect(master);
  src.start();
}

export function playSfx(name: Sfx) {
  if (muted) return;
  switch (name) {
    case "key":
      click(0.045, 0.018);
      break;
    case "typo":
      tone({ freq: 150, type: "sawtooth", dur: 0.09, gain: 0.09 });
      break;
    case "stage":
      tone({ freq: 660, dur: 0.06, gain: 0.09 });
      tone({ freq: 990, dur: 0.09, gain: 0.09, delay: 0.06 });
      break;
    case "correct":
      // A major arpeggio, played fast enough to read as one event.
      [523.25, 659.25, 783.99, 1046.5].forEach((f, i) =>
        tone({ freq: f, type: "triangle", dur: 0.09, gain: 0.13, delay: i * 0.05 }),
      );
      break;
    case "wrong":
      tone({ freq: 240, to: 130, type: "sawtooth", dur: 0.26, gain: 0.13 });
      break;
    case "hint":
      tone({ freq: 1320, type: "sine", dur: 0.18, gain: 0.11 });
      tone({ freq: 1760, type: "sine", dur: 0.22, gain: 0.07, delay: 0.07 });
      break;
    case "count":
      // The formation-lap beep: low, flat, unmistakably "not yet".
      tone({ freq: 440, dur: 0.14, gain: 0.16 });
      break;
    case "go":
      // Lights out. Two octaves together, held long enough to land.
      tone({ freq: 880, dur: 0.5, gain: 0.16 });
      tone({ freq: 1760, type: "triangle", dur: 0.5, gain: 0.1 });
      break;
    case "join":
      tone({ freq: 587.33, dur: 0.07, gain: 0.1 });
      tone({ freq: 880, dur: 0.11, gain: 0.1, delay: 0.07 });
      break;
    case "finish":
      // Chequered flag.
      [659.25, 783.99, 1046.5, 1318.5].forEach((f, i) =>
        tone({ freq: f, type: "triangle", dur: 0.22, gain: 0.14, delay: i * 0.11 }),
      );
      break;
    case "ui":
      click(0.03, 0.014);
      break;
  }
}

export const isMuted = () => muted;

export function setMuted(next: boolean) {
  muted = next;
  try {
    localStorage.setItem(STORE_KEY, next ? "off" : "on");
  } catch {
    /* private mode: the setting simply does not persist */
  }
  if (!next) {
    // Toggling sound on is itself the gesture that lets the context start, and
    // an unmute that makes no sound at all reads as broken.
    playSfx("ui");
  }
  listeners.forEach((l) => l(next));
}

export function onMuteChange(fn: (m: boolean) => void): () => void {
  listeners.add(fn);
  return () => listeners.delete(fn);
}
